apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: ap-southeast-1
  version: "1.28"
availabilityZones:
- "ap-southeast-1a"
- "ap-southeast-1b"
- "ap-southeast-1c"
managedNodeGroups:
- name: general
  labels:
    role: general
  instanceType: t3.small
  desiredCapacity: 3
  minSize: 3
  maxSize: 3
  volumeSize: 20

